language: objective-c
osx_image: xcode9.4
xcode_workspace: FocusPrototype.xcworkspace

before_install:
   - gem install cocoapods
   - pod install

script: 
   - xcodebuild test -workspace FocusPrototype.xcworkspace -scheme "FocusPrototype" -destination 'platform=iOS Simulator,name=iPhone 8,OS=latest'
